services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    environment:
      - ANYLOG_NODE_URL=http://66.175.217.145:32349/
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.src:ro
    command: /bin/sh -c "envsubst '$$ANYLOG_NODE_URL' < /etc/nginx/nginx.conf.src > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    dns:
      - 8.8.8.8
    restart: unless-stopped